# Generated by Django 4.2.7 on 2023-12-26 12:54

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_newuser_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(default=main.models.get_default_avatar, upload_to='avatars/'),
        ),
    ]
