# Generated by Django 4.2.7 on 2023-12-26 13:10

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_customuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(default=main.models.get_default_avatar, upload_to='avatars/'),
        ),
    ]
