# Generated by Django 4.2.7 on 2023-12-26 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_product_order'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Service',
        ),
    ]
